version: '3'
services:
  server:
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      - DBNAME=dealls
      - DBURI=mongodb://intv:pwd@mongodb:27017
      - SECRET=8EB0883F-992A-466D-970F-DF2F1A052233
      - PORT=8000
    ports:
      - 8000:8000
    depends_on:
      - mongodb
  mongodb:
    image: mongo:5.0.5
    volumes:
      - ./init-mongodb:/docker-entrypoint-initdb.d
      - ./init-mongodb/data:/tmp/data
    ports:
      - "27017:27017"
